### ISSUE TITLE
Add columns to CSV output

### ISSUE THREAD

**Issue by tmesposito** [elnjensen/Tapir#4]
Please include the same data in the CSV output as are in the HTML output. Specifically, I would like to have CSV columns for:
- "% of transit"
- "% of transit baseline observable"
- "Moon %"
- Additionally, it would be great to include the "TFOPWG disposition" from the TFOP database (i.e., planet candidate, false positive, etc.), just for TESS objects.

This would reduce the need to manually cross check the CSV output with the HTML table. Thanks!

**Comment by elnjensen** [comment]
Addressed by bf529c7.  In addition to the above-mentioned fields, CSV output now includes Moon distance (in degrees), recommended start and end times given specified baseline constraints, and (for TESS objects) the TOI number and TFOP priority.  Let me know if I've missed any fields. 

Note also that the name of the depth field has been corrected from "depth(mmag)" to "depth(ppt)".
